
services:

  backend:
    container_name: dotnet_backend
    image: backend:andari
    build: ./backend
    networks:
      - web-net
    env_file:
      - backend/.env.docker

  nginx:
    container_name: nginx
    image: nginx:andari
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - web-net
    env_file:
      - .env

  db:
    container_name: db
    image: db:andari
    build: ./database
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
    networks:
      - web-net
    env_file:
      - .env

volumes:
  pgdata:

networks:
  web-net:
    driver: bridge
